### ISSUE TITLE
Change color scheme for main website/documentation to improve readability

### ISSUE THREAD

**Issue by ajusa** [h3rald/min#107]
Hello,

I'm sorry to say this, but the the colors on the website (https://min-lang.org/learn/ for example) are really hard to read. I ran it through https://color.a11y.com/ and the text -> background contrast is 40% too low to pass the accessibility standards. 
For reference, I'm viewing the website on a 1080p monitor that might not be super color accurate. I also think that the font weight might be a tad too light, as the letters look pretty thin on my monitor, to the point where I can see the anti-aliasing attempts.

I suggest using a higher font weight (400?) and making the body text a fair amount lighter, while keeping the background roughly the same or a bit darker. 

To be clear, the website is *possible to read* but I wouldn't call it easily *readable*. Sorry if this seems like a bit of a nitpick, I know that you are busy with other language features.

**Comment by h3rald** [comment]
Hey! Thanks for the feedback! You are actually not the first one to say it actually... while it work fairly OK on a mobile device with Retina display, I think you are right, the site doesn't seem very readable on a desktop/laptop monitor...

I didn't do much about it because, well, I thought it was just me using s**tty monitors 🤣 but yes, you are right. I will do some tests on contrast as you suggest and tweak a few values here and there. Same goes for the font: every time I used a light font weight for something I always got complaints because it's not readable on desktops so... definitely, I'll go for a higher font weight overall.

And probably also use the higher contrast logo that @drkameleon madd while I am at it as well 😉 

Thanks!

**Comment by h3rald** [comment]
Fixed in v0.31.0 -- please take a look now!

**Comment by ajusa** [comment]
Look a lot better! I still think that you might want to consider changing the font weight. It's pretty thin on my (low dpi) monitor which makes it uncomfortable to read.

**Comment by h3rald** [comment]
You know I did try using higher weights but I wasn't convinced: on my laptop and monitor just looked waaay too thick. I gotta experiment a bit and also stop using Google fonts. 

Let's try this, how does this look on your monitor:

https://h3rald.com

I may just end up using the same font combinations as my personal site.

**Comment by ajusa** [comment]
Hm, the headings look fine but the font weights is too thin again.
![image](https://user-images.githubusercontent.com/7073362/106368999-0049c200-631c-11eb-924c-a667caab51af.png)
This is what it looks like on my monitor
