### ISSUE TITLE
quote != '

### ISSUE THREAD

**Issue by ghost** [h3rald/min#141]
The `quote` symbol isn't fully equivalent to `'` sigil. Because, see:

```
1 :a

a quote puts ; puts `(1)` on the screen
'a puts ; puts `(a)` on the screen
```

**Comment by h3rald** [comment]
OK this is weird. Going to look into it, could be something related to the recent change in the define operator (it now auto-quotes quotes as well, like the old quote-bind symbol).

Thanks you for spotting this!

**Comment by h3rald** [comment]
Alright, actually... I am going to say that this is "by design", because:

* if you use the sigil, the symbol is not pushed on the stack, so it gets quoted properly
* if you use quote, the symbol was already pushed on the stack, so its value is quoted instead.

Let's just say that `'a` is fully equivalent to `(a)` 😊

**Comment by h3rald** [comment]
Reopened (see #145).

**Comment by h3rald** [comment]
Fixed
