### ISSUE TITLE
Linux: GLIBC_2.29 not found.

### ISSUE THREAD

**Issue by step-** [h3rald/min#65]
Hi,  I downloaded the pre-build binary for Linux. It seems it needs a specific libc version, so it can't run on my system.
```sh
# min
min: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by min)
```

**Comment by h3rald** [comment]
Finally found some time to research this a little bit. It looks like when compiling on Linux it does require a specific libc version, unless you statically link musl (see [here](https://forum.nim-lang.org/t/2236)).

I compiled the executable on my Ubuntu system and... well, unfortunately that means that it would run on a x64 Linux system with GLIBC v2.29 *or higher*. I am going to leave this issue open for the time being, mainly because I don't have an easy fix at the moment and my free time is kinda limited these days.

What version of GLIBC do you have on your linux system? Did you try to compile min from scratch?

**Comment by step-** [comment]
Thank you for looking into this.  I have GLIBC v2.27.  I didn't try to compile min from scratch because I couldn't find instructions about building min.  I'm not a min or nim user.

**Comment by h3rald** [comment]
Fixed this by providing a cross compiled Linux binary statically linking libmusl. In this way it won't even look for libc.

(See also #63 for some problems I had with musl, now all fixed)

**Comment by step-** [comment]
Now it works for me.   Thank you!
