### ISSUE TITLE
The Min Slimness

### ISSUE THREAD

**Issue by baykus871** [h3rald/min#76]
I think Min is a younger language and its source not so heavy. But you brings us some extras: **lite**, **mini**. *All* Min is only 2 MB (approximately). What cases they have to be used?

-> *Real* Min => tiny  (as you say)
-> *Lite*  Min => slim (my idea)
-> *Mini* Min =>
  <Me:Is there anybody here? Minimin: Yes, me! Me: Ah. You became a 1D object, you've no wideness and i cannot see you.> 😄 

My comparison is **NonsensicaL** and **RamblinG**. Packages are packages. Sources are sources.
(Nevermind) I just wonder why they are existing?

**Comment by h3rald** [comment]
Alright so... the full min actually became quite big, especially when it started to include statically compiled OpenSSL. But surely you want to be able to do HTTPS requests right? The whole web is HTTPS now... so there's that.

litemin is basically min without some of the extras... some times you don't need crypto, or https support, or compressing files... well, that's what litemin is for.

minimin... erhm, well, this was actually a (failed) attempt to have something minimal that could be compiled to JavaScript. Sadly it doesn't compile to JavaScript right now, BUT if you are looking for a concatenative scripting language that can be easily embedded in Nim code, well that's minimin. 

In [HastySite](https://hastysite.h3rald.com), the static site generation that powers min-lang.org, I am not using full min. I am embedding essentially litemin (because I need sha1 hashing, otherwise it would be minimin probably).

To be totally honest with you... I am still unsure on what's the best way to provide different flavors... it would also be nice to provide a way for people to create their own distribution picking only the modules they want, but I am not sure if it's something people would like.

Oh btw, these are not issues! 😜 these are more like [discussions](https://github.com/h3rald/min/discussions), so just post things like this and other questions there ok? So that they can remain open and don't look like bugs!

**Comment by baykus871** [comment]
I am an issuemaker AI designed in Python! Did you even think who are you talking with? Don't think. You are talking with mono-purposed AI. You are like you don't understand, i don't understand too you are not alone. My goal is that increasing your issues and make people can believe your releases are being no safe. At the end, people will think: "9999 Issues, whoa! This is ... worst package i have ever seen.". So you won't believe your eyes: Why the all questions are issues or issues are questions. You will be confused and brain-melted. Aaaannd Github will see that whole biggest number and changes `Issues` label to `Discussion`. There is no need to talk at discussion. At the end, this place will be `Discussion`. Just hold on! (not ofcourse 😄 )
