### ISSUE TITLE
REPL and readline bindings

### ISSUE THREAD

**Issue by mwgkgk** [h3rald/min#9]
Most [readline](https://cnswww.cns.cwru.edu/php/chet/readline/readline.html) [shortcuts](http://readline.kablamo.org/emacs.html) are not supported by the REPL. The workaround wrapper called [rlwrap](https://github.com/hanslub42/rlwrap) is not working with `min -i` for some reason (does work for other projects).

**Comment by h3rald** [comment]
That's probably because min REPL internally uses [nimline](https://github.com/h3rald/nimline) for line editing. It's a tiny surrogate for readline, just it is implemented in pure Nim and works on Windows as well, without relying on libreadline.

Of course not all shortcuts work, I only focused on providing the essential ones like tab completion, history, go to end/start of line, kill line, etc. What are you missing exactly and what platform are you running on?

**Comment by mwgkgk** [comment]
Oh, I see. I think of readline as a de-facto standard that you can meet even in places like world of warcraft macro window / login screen, even this very editor :) The widespread bindings are emulating emacs ones, there's also a vi mode.

Things lacking (that I use):
```
Ctrl-a     move cursor to beginning of the line
Ctrl-f      move forward a character
Ctrl-b     should move backward a character (currently moves cursor to beginning of a line)
Alt-f        Move forward to the end of the next word. 
Alt-b       Move back to the start of the current or previous word
Ctrl-p     Previous item in history
Ctrl-n     Next item in history
Ctrl-k     Kill til end of line
Ctrl-u     Kill whole line
Ctrl-w    Kill word backward
```
I'm not sure how much can I ask of you :D So there you go. Not insisting on Ctrl-b behavior change.

rlwrap thing not working on Archlinux bash/zsh with or without tmux, I'll provide versions if needed
