### ISSUE TITLE
% Interpolation %

### ISSUE THREAD

**Issue by baykus871** [h3rald/min#95]
`"$1 puts" ("a") % eval` min code throws an error:
```
(!) <eval>(1,1) [a]: Undefined symbol 'a'
    <eval>(1,1) in symbol: a
    <repl>(1,22) in symbol: eval
    <repl>(1,23) in symbol: eval
    <repl>(1,23) in symbol: eval
```
But i expected that it will prints `"a"` on screen. What is wrong?

**Comment by h3rald** [comment]
That's correct...

Let's see:

     "$1 puts" ("a") % ; outputs: "a puts"

therefore:

     "a puts" eval

...it's like running: `a puts`, and in this case of course the symbol `a` is undefined!

If you want to print the string "a", then you'd have to write `"a"`:

     "$1 puts" ("\"a\"") % eval

**Comment by baykus871** [comment]
I did as like as you and 👍 Good, it returns: `"a"`. However now it focused to format everything that gived in, as string:
`"$1 puts" (" \"1\" ") % eval     ; "1"`
It puts `"1"` not `1`.

Is there a formatting option which adapted for this thing?

**Comment by h3rald** [comment]
Well... that's perfectly normal behavior for an eval function, even in other languages: if you want to evaluate strings you have to put them in double quotes, and because you are evaluating a string, you have to escape them.

Honestly I am providing `eval `for completeness only, typically you'd want to use `load` or `require`, or at any rate evaluate string that is provided from outside, not written as a string literal...

**Comment by baykus871** [comment]
The difference of string formatting,  made duplication at whole my code. Probably there is a no real solution for this.
